### ISSUE TITLE
Sending real-time media to WebRTC clients

### ISSUE THREAD

**Issue by riccardobrue** [paullouisageneau/libdatachannel#134]
I have the requirement of sending audio frames (Ubuntu-based system with ALSA and FFmpeg) captured by my PC's line-in through the WebRTC standard. Is it possible to do this work using this library? 

I am supposing that I have to create something like a AudioMediaTrack class which sends captured and encoded audio frames with this method "data_channel->send(audio_message);" right? Is there any example of someone doing this kind of work?

In order to make you a clearer idea, I have already developed something using [this ](https://aiortc.readthedocs.io/en/latest/api.html?highlight=track#aiortc.MediaStreamTrack) library in Python, but it is not so performant for the goal of my project which is to have a single server which has multiple P2P WebRTC connections and the server "multicasts" the captured audio frames to each of the connected clients.

**Comment by paullouisageneau** [comment]
This should work provided you create the data channel as unreliable and unordered (`ordered: false, maxRetransmits: 0`) otherwise delays introduced by retransmissions will be an issue.

However, I don't know of an example of this, probably because people will use the media transport of WebRTC instead. I'm actually working on implementing it in libdatachannel but it's an early proptotype right now.

**Comment by riccardobrue** [comment]
> This should work provided you create the data channel as unreliable and unordered (`ordered: false, maxRetransmits: 0`) otherwise delays introduced by retransmission will be an issue.
> 
> However, I don't know of an example of this, probably because people will use the media transport of WebRTC instead. I'm actually working on implementing it in libdatachannel but it's an early prototype right now.

Oh perfect! Thank you for your reply!

**Comment by stazio** [comment]
@riccardobrue What is the status of your media implementation? I am looking for a WebRTC media+data channel library that I can use but I don't see any documentation about this. I see your dtlssrtptransport implementation, but I don't see any additional logic around it.

**Comment by paullouisageneau** [comment]
@stazio Indeed the actual transport works but it still misses the logic to interpret the media in the SDP description. For now it can be used only through the `sendMedia`/`onMedia` methods if you have only one stream.

**Comment by stazio** [comment]
@paullouisageneau I spent some time over the weekend toying around with those functions. I'm still relatively new to WebRTC, but I am not able to see how I could mangle the SDP your library produces into working with a browser...

If I can get the browser to send me video and/or audio, I will be very interested to write the logic surrounding SDP interpretations, and work around getting RTCP to do recoveries.

I am currently using Janus, and it is giving me a lot of headaches to say the least.

**Comment by paullouisageneau** [comment]
> I'm still relatively new to WebRTC, but I am not able to see how I could mangle the SDP your library produces into working with a browser...

That's normal because for now it's tricky to use, the SDP has to be passed on the offerer side by calling `setLocalDescription` (before `createDataChannel`) and retrieved manually the answerer side where a method to properly set the local description is missing... I'll work on this when needed.

> If I can get the browser to send me video and/or audio, I will be very interested to write the logic surrounding SDP interpretations, and work around getting RTCP to do recoveries.

That would be great!

**Comment by paullouisageneau** [comment]
This should address the missing way to properly set the local description on the answerer side: https://github.com/paullouisageneau/libdatachannel/pull/140

**Comment by stazio** [comment]
I am still a little bit confused on what I should do. I have my browser sending an offer with one audio stream. I set that as the remote description, and then onLocalDescription is sending the answer back to the browser. The browser then complains that it is missing the ice-ufrag/ice-passwd for that stream.

**Comment by paullouisageneau** [comment]
There is a limitation for now when you send an offer from the browser: you have to open a dummy datachannel on the browser side, because libdatachannel will always try to setup datachannels irrelevant of the offer, which will confuse the browser.

**Comment by stazio** [comment]
I tried that, and still isn't working.
[This](https://gist.github.com/stazio/8769ae74f2315c3a91ab6ee8f1d55911) is the offer made by the browser, and [this](https://gist.github.com/stazio/09522a0364f9a9ecb02e6ea14dd45391) is libdatachannel's answer.

What I know is happening, is that I am failing to properly register those media channels with libjuice, and allow libjuice to modify the SDP, but I don't know what the right way would be to allow that to work.

Thank you for all of your help so far.

**Comment by paullouisageneau** [comment]
At first sight it looks good. Do you still get an error with ice-ufrag/ice-pwd missing? If not, where does it fails?

Also, have you tried enabling debug logging for libdatachannel?

**Comment by stazio** [comment]
With debug mode all I get is `2020-08-10 17:44:35.875 WARN  [141928] [rtc::IceTransport::LogCallback@267] juice: agent.c:1007: STUN message send failed, errno=101` as well with a bunch of warnings that it is ignoring TCP candidates, but I know that is expected.

The issue is that the ice-ufrag/pwd is after the "m=" for the data channel so it isn't part of the m=audio line.

**Comment by stazio** [comment]
[Here](https://gist.github.com/stazio/508f9e2ba69883b2bb1522b9ab6f74a6) is the code that I am using. I am using seasocks for the websocket server, but it's fairly easy to understand.

**Comment by paullouisageneau** [comment]
Could you please try with https://github.com/paullouisageneau/libdatachannel/pull/141 ? This would require more testing one my side, it seems I didn't put all the necessary media SDP handling in master.

Thanks for the code, I'll have a look.

**Comment by stazio** [comment]
Hey @paullouisageneau.
#141 pointed me in the right direction. I added #142 which fixes the issue with the ice-ufrags. I am now receiving this error `juice: agent.c:1007: STUN message send failed, errno=101`.

**Comment by paullouisageneau** [comment]
Thanks for the fix! However it breaks integration with libnice somehow, I'll investigate and merge when it is sorted out.

> I am now receiving this error juice: agent.c:1007: STUN message send failed, errno=101.

This is just a warning, very probably IPv6 not being available while the STUN server or the other peer has an IPv6 address. Is the peer connection established?

**Comment by paullouisageneau** [comment]
The SDP parser in libnice does not seem to accept session-level attributes for `ice-ufrag` and `ice-pwd` (it needs them to be after a m-line), which is actually not standard-compliant: https://github.com/libnice/libnice/blob/master/agent/agent.c#L6581

I'll work around that, it's not the first SDP workaround for libnice anyway :sweat_smile:

**Comment by alicera** [comment]
Hi 
how to generate the SDP  for libdachannel？
I already know 
	pc->onLocalDescription([](const Description &description) {
		cout << "Local Description (Paste this to the other peer):" << endl;
		cout << string(description) << endl;
	});

**Comment by stazio** [comment]
@paullouisageneau I put the ufrag/pwd into each m= line and it seems to work. I am updating #142 to account for this.

That said, I am now running into an issue with handing out candidates. For some reason, my browser is just not taking any candidates that we provide and juice isn't providing candidates for my media stream.

**Comment by paullouisageneau** [comment]
@stazio Don't worry I fixed it by generating an simplified internal SDP for libnice.

libjuice won't generate candidates for the media stream because it only supports one component, that's why libdatachannel will always use SDP bundle mode and send data + media on the same network stream.

The browser not accepting the candidates for the bundle is an issue though, do you get an error?

**Comment by stazio** [comment]
I'm not getting any errors at all.

> libjuice won't generate candidates for the media stream because it only supports one component, that's why libdatachannel will always use SDP bundle mode to send data + media on the same network stream and handle demultiplexing at reception.

What would be the solution for this then? Would libdatachannels have to be modified to not require data channels?

**Comment by paullouisageneau** [comment]
> > libjuice won't generate candidates for the media stream because it only supports one component, that's why libdatachannel will always use SDP bundle mode to send data + media on the same network stream and handle demultiplexing at reception.
> 
> What would be the solution for this then? Would libdatachannels have to be modified to not require data channels?

Well that's not a problem, only it requires the other side to understand the bundle mode also. Modern browsers are OK with that. It's not only used for media + data, but also for audio + video for instance.

> I'm not getting any errors at all.

Don't you get an error in the resulting promise? A common issue is that you have to specify `sdpMid`, it's mandatory in the JavaScript API (it's available as `candidate.mid()` from libdatachannel).

**Comment by stazio** [comment]
I am passing candidate.mid() as sdpMLineIndex because when I do sdpMid I do indeed get an error: `Cannot set ICE candidate for level=<Nothing> mid=1: No such transceiver.`

**Comment by paullouisageneau** [comment]
It should definitely be passed as `sdpMid`, and it seems we got the root of the problem here. I think the browser expects the audio mid because the audio comes first in the bundle while libdatachannel sends the data one. If that's indeed the case it should be fixed in #141.

**Comment by stazio** [comment]
It doesn't seem to be working. I'm getting the same error - That said I don't know if this is helpful, but the browser is generating it's candidates for two sdpMid/mLines.

I need to learn about how bundling works.

**Comment by paullouisageneau** [comment]
Oh, I forgot, you might need to set `bundlePolicy` to `max-bundle` in `RTCConfiguration` if the browser is offering: https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration#RTCBundlePolicy_enum

After setting it, what is the `sdpMid` of generated candidates?

**Comment by stazio** [comment]
The candidates are all `sdpMid: 0` now but it's still failing.

**Comment by paullouisageneau** [comment]
Does libdatachannel also generate `sdpMid: 0`? I think I need to do some debugging on my side. Is the browser Chrome?

**Comment by stazio** [comment]
I just tested it in chrome and we are getting further. libdatachannel is reporting as connected! Although the onMedia isn't getting triggered. I was using firefox before. 

I made a new git with what I have done so far [here](https://github.com/stazio/webrtc). You have to clone it recursively and  checkout `fix-sdp-media`.

**Comment by stazio** [comment]
@paullouisageneau I added PR #143 to fix the DTLS-SRTP implementation in GNU-TLS.

**Comment by paullouisageneau** [comment]
@stazio I redesigned the transport initialization by moving thread start out of constructor in #147, it should fix the issue with GnuTLS reliably.

**Comment by stazio** [comment]
@paullouisageneau Awesome! The fix works well. Over the past couple of days, I have been battling to get RTCP recognized by the browser browser (I saw your comment on #143). I am working all of that out myself. However, in the mean time, I am running into an issue. Shortly after the log `SCTP resetting stream 1`, every connection is terminated. This happens after about half a minute. Would you know what is going on?

**Comment by paullouisageneau** [comment]
`SCTP resetting stream 1` is part of the Data Channel shutdown process. However, since every connection is terminated, I guess the entire SCTP association is actually shutdown. Something must be triggering it, do you see an error before in the log?

**Comment by stazio** [comment]
Looking back, yeah, for some reason juice is `Changing state to completed` after a little while. A while before it closes the connection.

**Comment by paullouisageneau** [comment]
`completed` actually means all candidates have been checked in ICE terms, not that it's finished.

Maybe the browser initiates the shutdown. Could you please turn on verbose logging and look for "Process notification" before "SCTP resetting stream" in the log?

**Comment by stazio** [comment]
`[rtc::SctpTransport::processNotification@603] Process notification, type=10` shows up fairly frequently but that is all.

**Comment by paullouisageneau** [comment]
Hum, the remote side closing would be type 9... Could you send me the verbose log please?

**Comment by stazio** [comment]
[https://gist.github.com/stazio/702e9c36243b978ee4b3aa30fdc30b3d](https://gist.github.com/stazio/702e9c36243b978ee4b3aa30fdc30b3d).

**Comment by paullouisageneau** [comment]
The only `SCTP resetting stream` I see is at the end, because `PeerConnection::close()` is called. Am I missing something? :thinking:

**Comment by stazio** [comment]
Haha, you are not, but apparently I am missing my understanding of seasocks. Thanks for spotting that.... I apologise for the bother.

**Comment by paullouisageneau** [comment]
Sure, no problem! Keep me updated about that RTCP issue.

**Comment by stazio** [comment]
@paullouisageneau I got RTCP receiver reports to work! Probably on Monday I will try to clean up what I have done so far and send it your way. I seem to be running into a issue regarding getting the bitrate to not take a dive almost immediately. I haven't tried to do any form of bandwidth control yet (nor have I negotiated for REMB/TWCC). Do you know of any reason that it would be dipping, or is it just an expectation to send some kind of feedback?

**Comment by paullouisageneau** [comment]
Great, congrats! 

Hum no, I don't see why I would dip like that. What audio source are you transmitting? It could simply become silent.

**Comment by stazio** [comment]
I am transmitting the webcam actually. The browser concludes very quickly that the bitrate can't exceed 30kbps (dropping from 300kbps over a few seconds).

**Comment by paullouisageneau** [comment]
For the record, I've fitted your implementation https://github.com/paullouisageneau/libdatachannel/pull/143 into a new API in https://github.com/paullouisageneau/libdatachannel/pull/153 and merged it into master.

I took the liberty of refactoring a few things, in particular the use of bit fields in `rtp.h` as they are not guaranteed to packed.

**Comment by paullouisageneau** [comment]
To sum up what has been done in the list drawn up by @stazio in #143 :
> Integrate the API more closely with rtc::PeerConnection.
> Create all of the handles to send media back to the browser.
> Add a RTP demuxer that can send multiple different RTP sessions to the RTCPSession classes. This will allow us to transmit multiple tracks over one peer connection.

What is still to be done:
> Add the ability to send NACK's, ACK's, and PLI requests.
> Add more RFCs such as TWCC.
> Implement the specifications regarding relaying.

**Comment by paullouisageneau** [comment]
For the record, after merging #162, the media example now also works properly with Firefox.

**Comment by paullouisageneau** [comment]
Following the merge of #176, media transport is now broadly working, even if specific features will need to be sorted out.
