### ISSUE TITLE
SCTP disconnected within 15 mins

### ISSUE THREAD

**Issue by connieliuatskyrec** [paullouisageneau/libdatachannel#284]
I'm using v0.10.1 on Ubuntu18.04

`2020-12-07 20:42:27.290 INFO  [20064] [rtc::SctpTransport::processNotification@652] SCTP disconnected`

Got this log with no peers try to terminate connections. Disconnection happens in 15 mins.

**Comment by paullouisageneau** [comment]
Does it disconnects after 15min each time?

libdatachannel sends SCTP heartbeats aggressively every 10 secs, and 15 mins is a pretty long time, so it doesn't look like a network timeout. What is the connection doing when it disconnects? Also, are both peers running libdatachannel?

**Comment by connieliuatskyrec** [comment]
Sorry about the description was not clear. Not every disconnection happens after 15 mins. Sometimes just within a few minutes. It happens with no clues. Would it be helpful if I provide more log messages? Yes, both peers are running libdatachannel.

**Comment by paullouisageneau** [comment]
Yes thank you, if you could please link the verbose log of the two sessions it should give a clue of where it comes from.

**Comment by connieliuatskyrec** [comment]
[peer1.log](https://github.com/paullouisageneau/libdatachannel/files/5708535/peer1.log)
[peer2.log](https://github.com/paullouisageneau/libdatachannel/files/5708537/peer2.log)

Here are verbose log. At line 115 of peer2.log is
`2020-12-17 13:51:51.696 WARN  [15] [rtc::SctpTransport::doRecv@385] SCTP recv failed, errno=103`
whereas peer1 doesn't have this after SCTP disconnected showed.

**Comment by paullouisageneau** [comment]
It's a bit puzzling, it seems usrsctp on peer2 initiates a connection closure. Could you please update to at least v0.10.2, since I did a possibly related fix? Also, is the usrsctp submodule properly updated?

The SCTP recv warning is a false positive due to a useless attempt to read one last time whereas the connection is cleanly closed. It should be fixed by https://github.com/paullouisageneau/libdatachannel/pull/299

**Comment by connieliuatskyrec** [comment]
Logs provided are from v0.10.4. It still happens. All submodules are considered properly updated. Cloning commands:
```
git clone --recursive https://github.com/paullouisageneau/libdatachannel.git
cd libdatachannel
git checkout v0.10.4
```

Also, several default values are modified for use:
in `include/rtc/include.hpp`:
- DEFAULT_MAX_MESSAGE_SIZE = 65536 -> 2 * 1024 * 1024
- LOCAL_MAX_MESSAGE_SIZE = 256 * 1024 -> 2 * 1024 * 1024

and in `src/sctptransport.cpp`:
- bufferSize = 1024 * 1024 -> 3 * 1024 * 1024

**Comment by paullouisageneau** [comment]
I'm trying to reproduce the issue with these parameters, for now with no luck. What is the network setup, and how much do you send over the connection?

**Comment by connieliuatskyrec** [comment]
What do you mean by network setup? Could you please give some instructions so I can follow? I have no precise number on how much data being sent, but the size of each message must not exceed DataChannel::maxMessageSize().

Try to put peer1 to another network. Line 83 in peer2.log says: 
`2021-01-19 15:42:09.299 WARN  [31] [rtc::IceTransport::LogCallback@321] juice: agent.c:397: Send failed, errno=90`
and repeats similar pattern. The warnings are new to that was previously provided.
[peer1.log](https://github.com/paullouisageneau/libdatachannel/files/5842595/peer1.log)
[peer2.log](https://github.com/paullouisageneau/libdatachannel/files/5842596/peer2.log)

**Comment by paullouisageneau** [comment]
> What do you mean by network setup? Could you please give some instructions so I can follow? I have no precise number on how much data being sent, but the size of each message must not exceed DataChannel::maxMessageSize().

I mean is the test on a local network or is it across the Internet? Is IPv6 enabled? Is there one or two NAT one the path? Is there a VPN or something specific?

> Try to put peer1 to another network. Line 83 in peer2.log says:
> `2021-01-19 15:42:09.299 WARN [31] [rtc::IceTransport::LogCallback@321] juice: agent.c:397: Send failed, errno=90`
> and repeats similar pattern. The warnings are new to that was previously provided.
> [peer1.log](https://github.com/paullouisageneau/libdatachannel/files/5842595/peer1.log)
> [peer2.log](https://github.com/paullouisageneau/libdatachannel/files/5842596/peer2.log)

`errno=90` means the datagram is too big. It probably means the MTU discovery of usrsctp does not work as expected, and it ends up sending lots of datagrams that are too big. It looks indeed like the implementation is non functional: https://github.com/sctplab/usrsctp/issues/205

**Comment by paullouisageneau** [comment]
Could you please check if https://github.com/paullouisageneau/libdatachannel/pull/313 solves the issue for you?

**Comment by connieliuatskyrec** [comment]
> Could you please check if #313 solves the issue for you?

It works! Thanks for your help!

> I mean is the test on a local network or is it across the Internet? Is IPv6 enabled? Is there one or two NAT one the path? Is there a VPN or something specific?

Across the Internet. IPv6 disabled. Two NAT. No VPN.
